server_name: go.scout.ch
connections: 4096
forwards:
  de:
    qrcube:
      zelt: https://pfadi.swiss/wuerfel/lagerplatz-pfadiheim-verzeichnis
      buch: https://pfadi.swiss/de/wuerfel/digitale-hilfsmittel/
      feuer: https://pfadi.swiss/de/wuerfel/it-community/
      kompass: https://pfadi.swiss/wuerfel/it-tools/
    itkompass: https://itkompass.scout.ch
  fr:
    qrcube:
      tente: https://pfadi.swiss/fr/
      livre: https://pfadi.swiss/fr/
      feu: https://pfadi.swiss/fr/
      compass: https://pfadi.swiss/fr/
  qr:
    itkom-plakat: https://itkompass.scout.ch
