name: Build 

on:
  push:
    branches:
      - main

jobs:
  build-and-push-container:
    name: Build and Push Shortner Container
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker container
        uses: docker/build-push-action@v6
        with:
          context: ./
          load: true
          tags: |
            ghcr.io/scout-ch/go.scout.ch/nginx:latest
      - name: Push docker container
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./
          tags: |
            ghcr.io/scout-ch/go.scout.ch/nginx:latest
