name: Build 

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-push-container:
    name: Build and Push Shortner Container
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker container
        uses: docker/build-push-action@v6
        with:
          context: ./
          load: true
          tags: |
            ghcr.io/jamboree-it-switzerland/go.jamboree.ch/nginx:latest
      - name: Push docker container
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./
          tags: |
            ghcr.io/jamboree-it-switzerland/go.jamboree.ch/nginx:latest

  deploy:
      runs-on: ubuntu-latest
      permissions:
        id-token: write #This is required for requesting the JWT
        contents: read #This is required for actions/checkout
  
      needs: build-and-push-container
      
  
      steps:
        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZURE_DEPLOY_APP_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'go-jamboree'
            slot-name: 'Production'
            images: 'ghcr.io/jamboree-it-switzerland/go.jamboree.ch/nginx:latest'
